[general]
disable_reminders = false             # Set reminders on O_o events or not
verbosity_level = 1                   # How much chatter to spill out when running sync 1 = errors only, 2 = info, 3 = debug
block_event_visibility = "private"    # Keep O_o event public or private
authorized_ports = [8080, 8081, 8082] # Ports to listen on for OAuth token callback (the same you configured your app with in Google console!)

[google]
client_id = ""     # Get these from the Google Developer Console
client_secret = "" # Get these from the Google Developer Console

# CalDAV servers configuration
# Each server is defined in its own section under [caldav_servers.NAME]
[caldav_servers]

# Example work server
[caldav_servers.work]
server_url = ""    # CalDAV server URL (e.g., https://work.example.com/dav/)
username = ""      # CalDAV server username
password = ""      # CalDAV server password
name = "Work Calendar"  # Optional friendly name

# Example personal server
[caldav_servers.personal]
server_url = ""    # CalDAV server URL (e.g., https://personal.example.com/dav/)
username = ""      # CalDAV server username
password = ""      # CalDAV server password
name = "Personal Calendar"  # Optional friendly name